version: '3.8'

services:
  # Flutter web app
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.2do-health.rule=Host(`localhost`)"
      - "traefik.http.services.2do-health.loadbalancer.server.port=80"

  # Development server (uncomment for development)
  # dev:
  #   image: cirrusci/flutter:stable
  #   volumes:
  #     - .:/app
  #   working_dir: /app
  #   ports:
  #     - "3000:3000"
  #   command: >
  #     bash -c "
  #       flutter pub get &&
  #       flutter run -d web-server --web-hostname 0.0.0.0 --web-port 3000
  #     "

  # Nginx reverse proxy (optional)
  # proxy:
  #   image: nginx:alpine
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #     - ./ssl:/etc/nginx/ssl:ro
  #   depends_on:
  #     - app
  #   restart: unless-stopped

  # Health check service
  healthcheck:
    image: curlimages/curl:latest
    depends_on:
      - app
    command: >
      sh -c "
        echo 'Waiting for app to be ready...' &&
        sleep 10 &&
        curl -f http://app:80 || exit 1 &&
        echo 'App is healthy!'
      "
    restart: "no"